# C?ng ch?y server
server.port=8081
spring.application.name=HRM_System

# K?t n?i PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/HRM
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# C?u hình JPA/Hibernate
# create: T?o m?i t? ??u (Xóa h?t d? li?u c?) - Dùng lúc m?i b?t ??u
# update: Gi? d? li?u c?, ch? c?p nh?t c?t m?i - Dùng khi ?ã ?n ??nh
# validate: Ch? ki?m tra xem Java và DB có kh?p nhau không - Dùng cho DB này vì b?n ?ã t?o b?ng b?ng SQL r?i
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect