package com.project.hrm.module.corehr.exception;

public enum ErrorCode {

    EMPLOYEE_NOT_FOUND,
    EMPLOYEE_NOT_ACTIVE,
    PENDING_REQUEST_EXISTS,
    NO_DATA_CHANGED,
    OFFBOARDING_PENDING_EXISTS,
    OFFBOARDING_NOT_FOUND,
    OFFBOARDING_INVALID_STATUS,
    OFFBOARDING_INVALID_TYPE,
    OFFBOARDING_CANCEL_NOT_ALLOWED,
    APPROVAL_REQUEST_EXISTS,
    APPROVAL_REQUEST_NOT_FOUND,
    INVALID_APPROVAL_ACTION,
    INVALID_CREDENTIALS,
    ACCOUNT_LOCKED,
    ACCOUNT_INACTIVE,
    ACCESS_DENIED,
    ACTIVATION_TOKEN_INVALID,
    ACTIVATION_NO_USER_ACCOUNT
}