spring.application.name=hrm

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/hrm
spring.datasource.username=postgres
spring.datasource.password=sa
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# JWT
app.jwt.secret-key=cmtwIWlYRTQ4MltVTEs7Lzp3S18pY2teNkghPmsjRWFMWnJRWUVoeXRAcQ==
app.jwt.access-token-expiry=900000
app.jwt.refresh-token-expiry=604800000


# Frontend
app.frontend-url=http://localhost:5173