spring.application.name=hrm

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/hrm
spring.datasource.username=postgres
spring.datasource.password=sa
spring.datasource.driver-class-name=org.postgresql.Driver

app.contract.storage-path=/var/hrm/contracts