spring.application.name=hrm

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/backup
spring.datasource.username=postgres
spring.datasource.password=sa
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# OAuth2 Google
spring.security.oauth2.client.registration.google.client-id=1009532807092-qu3qga07l46t6m28e55ag3g8onbc589d.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# JWT
app.jwt.secret-key=cmtwIWlYRTQ4MltVTEs7Lzp3S18pY2teNkghPmsjRWFMWnJRWUVoeXRAcQ==
app.jwt.access-token-expiry=900000
app.jwt.refresh-token-expiry=604800000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dinhfuk5@gmail.com
spring.mail.password=azsw gcif vois kowu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Frontend
app.frontend-url=http://localhost:5173